services:

  openaiserver:
    image: openaiserver
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      Llama__3_1__8B_Quant_Instruct: ${Llama__3_1__8B_Quant_Instruct}
      MedLlama__3__8B_Quant: ${MedLlama__3__8B_Quant}
      Biomistral__7B_Quant: ${Biomistral__7B_Quant}
    volumes:
      - ${MODEL_FOLDER}:${MODEL_FOLDER}
      - ./output/cache.db:/openai-server/output/cache.db
    command: openaiserver